### ISSUE TITLE
Android deploy issue

### ISSUE THREAD

**Issue by PFloyd0** [jpmml/jpmml-evaluator#244]
It's me again LOL, sorry to bother you....
I succeed to do evaluate using my pmml model in my windows java environment but when I deploy it in the android device some problems occurs.
I see some similar issues which they said can be solved by using some android version packages instead of java. I do not know whether it is the same issue.
<img width="692" alt="dddd" src="https://user-images.githubusercontent.com/73516559/162110964-49db846a-51ff-4e7f-9f3a-c8326866f1b6.PNG">

This is my dependency:
<img width="527" alt="aa" src="https://user-images.githubusercontent.com/73516559/162110991-ee2c8f7a-47cf-412a-aa29-250a83d22b56.PNG">

**Comment by vruusmann** [comment]
> This is my dependency

Step-by-step instructions:

1. Upgrade from JPMML-Evaluator 1.4.15 to 1.6.3. The current codebase is guaranteed to be Android 5.0 (API level 21) compatible: https://github.com/jpmml/jpmml-evaluator/blob/1.6.3/pom.xml#L307-L328
2. The `NoClassDefFoundError` is actually raised by the JAXB runtime transitive dependency. I believe that the JPMML-Evaluator upgrade might solve this issue, because it includes a much newer version of the JAXB runtime than before.
3. The default JAXB runtime is Glassfish Metro. If that can't be made to work, use EclipseLink MOXY.
4. Switch from XML to a different model persistence data format. For example, JSON or Java serialization.
5. Translate the PMML XML document into a standalone Java class using the [JPMML-Transpiler](https://github.com/jpmml/jpmml-transpiler) library.

**Comment by PFloyd0** [comment]
I'm really sorry. After I updated to 1.6.3, the model can't run on local and Android devices. Forgive me for my inexperience in this field. I've tried many ways. Can you help me identify which dependencies I should uncomment
<img width="619" alt="1e" src="https://user-images.githubusercontent.com/73516559/162152224-c743bab6-6e73-45d6-811f-c13e73a71cbd.PNG">
<img width="417" alt="55e" src="https://user-images.githubusercontent.com/73516559/162152231-d90ad57a-ce4f-44b5-8ba8-040302a9b5a8.PNG">

**Comment by vruusmann** [comment]
> Can you help me identify which dependencies I should uncomment

Delete all your existing dependencies - they are out of date.

You only need to depend on the `org.jpmml:pmml-evaluator-metro:1.6.3`, as explained in the README file:
https://github.com/jpmml/jpmml-evaluator#installation

If the default Glassfish Metro JAXB runtime does not work, then you should replace the `org.jpmml:pmml-evaluator-metro:1.6.3` dependency with `org.jpmml:pmml-evaluator-moxy:1.6.3` dependency, and so on.

Whatever you do, don't manage JAXB runtime libraries manually! It's very difficult to get it right, if you're not a great expert in the area.

**Comment by PFloyd0** [comment]
org.jpmml:pmml-evaluator-metro will occur:

<img width="692" alt="dddd" src="https://user-images.githubusercontent.com/73516559/162160926-07aae941-50c0-44f2-a597-588c3fb5dab8.PNG">

org.jpmml:pmml-evaluator-moxy:1.6.3 will occur:
<img width="611" alt="lcw" src="https://user-images.githubusercontent.com/73516559/162161078-caddcca3-cd97-4933-9629-02591e7e6a63.PNG">
 So should I transform the .pmml file into .ser file to do prediction?
Thank you!

**Comment by vruusmann** [comment]
> org.jpmml:pmml-evaluator-moxy:1.6.3 will occur:

Your application is still looking for the default Glassfish Metro "entry point".

You would need to set the `org.glassfish.jaxb.runtime.v2.ContextFactory` system property to override this default.

There's an explanation here (at the end of the "Example Applications" section): https://github.com/jpmml/jpmml-model#example-applications

Sure, it would be nice if this switch was also detailed on the JPMML-Evaluator project README file.

**Comment by vruusmann** [comment]
> So should I transform the .pmml file into .ser file to do prediction?

The workflow would be:
1. In your local computer, which has full Java SE installed, load the `org.dmg.pmml.PMML` object from the PMML XML file.
2. Serialize this `PMML` object using `java.io.ObjectOutputStream`.
3. In your Android App, load this `PMML` object using `java.io.ObjectInputStream`. Use the `ModelEvaluatorBuilder(PMML)` constructor (instead of the default `LoadingModelEvaluatorBuilder()`) for initiating the evaluator building process.

Please note that the above workflow does not require a JAXB runtime. So, you may replace the `org.jpmml:pmml-evaluator-(metro|moxy)` dependency with the core `org.jpmml:pmml-evaluator:1.6.3` core dependency. Your Android App will be much leaner size-wise as a result of this.

Alternatively, you may use Kryo serialization by including the `org.jpmml:pmml-evaluator-kryo:1.6.3` dependency.

**Comment by vruusmann** [comment]
> So where can I change this setting?

In Java SE you can use `java.lang.System#setProperty(String name, String value)`.

I don't know if this utility method is directly available in Android or not. Search stackoverflow.

**Comment by vruusmann** [comment]
> You would need to set the org.glassfish.jaxb.runtime.v2.ContextFactory system property to override this default.

Alternatively, you can override the `LoadingModelEvaluatorBuilder#load(...)` method, and directly work with `org.eclipse.persistence.jaxb.*` classes there.

The base implementation queries the runtime system for the preferred JAXB runtime implementation. But this querying is unnecessary if you already know what you want to do.

Again, would be nice to have a Builder property for configuring such things more easily.

**Comment by PFloyd0** [comment]
<img width="630" alt="eqrqreqr" src="https://user-images.githubusercontent.com/73516559/162404228-f007d6a8-78b2-40e3-a6f1-bd88a66b7bef.PNG">
Sorry, is there something wrong with my code? Still some problems and I have checked the "pmml instanceof Serializable", it seems no problem....

**Comment by vruusmann** [comment]
> Still some problems and I have checked the "pmml instanceof Serializable"

The underlying JAXB runtime is inserting SAX Locator meta-information into the `org.dmg.pmml.PMML` class model object, which is not Java serializable by default.

You need to turn off the SAX Locator information (it bloats the object size by 25-35%, which is not good for Android Apps anyway).

Basically, emulate this:
https://github.com/jpmml/jpmml-evaluator/blob/1.6.3/pmml-evaluator/src/main/java/org/jpmml/evaluator/LoadingModelEvaluatorBuilder.java#L165-L167

**Comment by PFloyd0** [comment]
Sorry, I transfer to ser file successfully. But still some problems when deploy in Android.
Is there anything wrong? It can run in my windows environment but still not work in Android.
<img width="267" alt="04201" src="https://user-images.githubusercontent.com/73516559/164162304-b553d918-0d84-47fc-adce-5c5d38783c68.PNG">

<img width="423" alt="04202" src="https://user-images.githubusercontent.com/73516559/164162314-f450fdc3-c5f8-45af-91d2-95b4e0e08dfb.PNG">

**Comment by PFloyd0** [comment]
Should I overwrite the resolveClass function?

**Comment by vruusmann** [comment]
> Is there anything wrong?

The Java deserializer component can't find `com.sun.org.apache.xerces.internal.dom.ElementNSImpl` class definition.

As the class name shows, this is some re-packaged (aka shaded) version of the standard `org.apache.xerces.dom.ElementNSImpl` class (note the added `com.sun` prefix).

This class is not used by the JPMML family of libraries. I have no idea why is it part of your serialized class model object.

The most likely cause is that you're loading the PMML XML document using some Xerces-powered library stack, and Xerces is using this class to represent `InlineTable/row` element cells.

> Should I overwrite the resolveClass function?

You'd need to get rid of this offending `com.sun.org.apache.xerces.internal.dom.ElementNSImpl` class.

At minimum, try to get it replaced with the standard `org.apache.xerces.dom.ElementNSImpl` class, so that you could fix the classpath by simply adding the Xerces library to your application classpath.

**Comment by PFloyd0** [comment]
This is the previous dependency, which is from other guys' advice.
<img width="423" alt="04202" src="https://user-images.githubusercontent.com/73516559/165011476-f1b616a3-f96b-4d4a-9f41-6cadbdcb2bbf.PNG">
So how can I adjust this to make sure to use org.apache.xerces.dom.ElementNSImpl. I did not find this package information  in https://repo.maven.apache.org/maven2/org/apache/

**Comment by PFloyd0** [comment]
![image](https://user-images.githubusercontent.com/73516559/166617088-77a9e853-98b2-410c-a6f9-22b31eba6e40.png)
I also try to download the jar file in https://xerces.apache.org and use the local dependency, still the same error.....Hope for your help. Thank you very much!
